server:
  port: 8001

spring:
  application:
    name: microServiceCloudProviderDept
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:h2:mem:testdb1
    username: sa
    password: password
    driverClassName: org.h2.Driver
    data: classpath:data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-provider-${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.example: debug
